"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import batchitemerror as shared_batchitemerror
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class BatchPutGeofenceError:
    r"""Contains error details for each geofence that failed to be stored in a given geofence collection."""
    
    error: shared_batchitemerror.BatchItemError = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('Error') }})  
    geofence_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('GeofenceId') }})  
    